//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from XmlConsumer.g4 by ANTLR 4.7

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace OpCheck.XmlConsumer {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="XmlConsumerParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7")]
[System.CLSCompliant(false)]
public interface IXmlConsumerVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="XmlConsumerParser.xmlConsumerExpressionFile"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitXmlConsumerExpressionFile([NotNull] XmlConsumerParser.XmlConsumerExpressionFileContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XmlConsumerParser.xmlConsumerScript"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitXmlConsumerScript([NotNull] XmlConsumerParser.XmlConsumerScriptContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XmlConsumerParser.optionsTuple"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOptionsTuple([NotNull] XmlConsumerParser.OptionsTupleContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XmlConsumerParser.optionsList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOptionsList([NotNull] XmlConsumerParser.OptionsListContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ExpressionTypeOption</c>
	/// labeled alternative in <see cref="XmlConsumerParser.option"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpressionTypeOption([NotNull] XmlConsumerParser.ExpressionTypeOptionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>EncodingOption</c>
	/// labeled alternative in <see cref="XmlConsumerParser.option"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEncodingOption([NotNull] XmlConsumerParser.EncodingOptionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>PrefixOption</c>
	/// labeled alternative in <see cref="XmlConsumerParser.option"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrefixOption([NotNull] XmlConsumerParser.PrefixOptionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>BindingOption</c>
	/// labeled alternative in <see cref="XmlConsumerParser.option"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBindingOption([NotNull] XmlConsumerParser.BindingOptionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>BindingsOption</c>
	/// labeled alternative in <see cref="XmlConsumerParser.option"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBindingsOption([NotNull] XmlConsumerParser.BindingsOptionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ParseMethodOption</c>
	/// labeled alternative in <see cref="XmlConsumerParser.option"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParseMethodOption([NotNull] XmlConsumerParser.ParseMethodOptionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>AutoParseModeOption</c>
	/// labeled alternative in <see cref="XmlConsumerParser.option"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAutoParseModeOption([NotNull] XmlConsumerParser.AutoParseModeOptionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>AutoCreateModeOption</c>
	/// labeled alternative in <see cref="XmlConsumerParser.option"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAutoCreateModeOption([NotNull] XmlConsumerParser.AutoCreateModeOptionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>NullObjectTreatmentModeOption</c>
	/// labeled alternative in <see cref="XmlConsumerParser.option"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNullObjectTreatmentModeOption([NotNull] XmlConsumerParser.NullObjectTreatmentModeOptionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>CollectivityOption</c>
	/// labeled alternative in <see cref="XmlConsumerParser.option"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCollectivityOption([NotNull] XmlConsumerParser.CollectivityOptionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XmlConsumerParser.stringLiteralsList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStringLiteralsList([NotNull] XmlConsumerParser.StringLiteralsListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XmlConsumerParser.objectMappingBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitObjectMappingBlock([NotNull] XmlConsumerParser.ObjectMappingBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XmlConsumerParser.mappingList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMappingList([NotNull] XmlConsumerParser.MappingListContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>NullMapping</c>
	/// labeled alternative in <see cref="XmlConsumerParser.simpleMapping"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNullMapping([NotNull] XmlConsumerParser.NullMappingContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>NullMappingWithOptions</c>
	/// labeled alternative in <see cref="XmlConsumerParser.simpleMapping"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNullMappingWithOptions([NotNull] XmlConsumerParser.NullMappingWithOptionsContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>StringMapping</c>
	/// labeled alternative in <see cref="XmlConsumerParser.simpleMapping"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStringMapping([NotNull] XmlConsumerParser.StringMappingContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>StringMappingWithOptions</c>
	/// labeled alternative in <see cref="XmlConsumerParser.simpleMapping"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStringMappingWithOptions([NotNull] XmlConsumerParser.StringMappingWithOptionsContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ObjectMapping</c>
	/// labeled alternative in <see cref="XmlConsumerParser.complexMapping"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitObjectMapping([NotNull] XmlConsumerParser.ObjectMappingContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ObjectMappingWithOptions</c>
	/// labeled alternative in <see cref="XmlConsumerParser.complexMapping"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitObjectMappingWithOptions([NotNull] XmlConsumerParser.ObjectMappingWithOptionsContext context);
}
} // namespace OpCheck.XmlConsumer
