//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from XmlConsumer.g4 by ANTLR 4.7

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace OpCheck.XmlConsumer {
using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7")]
[System.CLSCompliant(false)]
public partial class XmlConsumerLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		T__9=10, T__10=11, T__11=12, T__12=13, T__13=14, T__14=15, T__15=16, T__16=17, 
		T__17=18, STRING_LITERAL=19, OBJECT_MEMBER_IDENTIFIER=20, WHITESPACE=21, 
		LINE_COMMENT=22;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "T__1", "T__2", "T__3", "T__4", "T__5", "T__6", "T__7", "T__8", 
		"T__9", "T__10", "T__11", "T__12", "T__13", "T__14", "T__15", "T__16", 
		"T__17", "STRING_LITERAL", "OBJECT_MEMBER_IDENTIFIER", "WHITESPACE", "LINE_COMMENT"
	};


	public XmlConsumerLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public XmlConsumerLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'('", "')'", "';'", "'ExpressionType'", "':'", "'Encoding'", "'Prefix'", 
		"','", "'Binding'", "'Bindings'", "'ParseMethod'", "'AutoParseMode'", 
		"'AutoCreateMode'", "'NullObjectTreatmentMode'", "'Collectivity'", "'{'", 
		"'}'", "'null'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, "STRING_LITERAL", "OBJECT_MEMBER_IDENTIFIER", 
		"WHITESPACE", "LINE_COMMENT"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "XmlConsumer.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static XmlConsumerLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\x18', '\xEB', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x3', '\x2', '\x3', 
		'\x2', '\x3', '\x3', '\x3', '\x3', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', 
		'\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', 
		'\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', 
		'\x3', '\b', '\x3', '\t', '\x3', '\t', '\x3', '\n', '\x3', '\n', '\x3', 
		'\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', 
		'\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', 
		'\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\f', '\x3', '\f', 
		'\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', 
		'\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\r', 
		'\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', 
		'\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', 
		'\x3', '\r', '\x3', '\r', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', 
		'\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', 
		'\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', 
		'\xE', '\x3', '\xE', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', 
		'\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', 
		'\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', 
		'\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', 
		'\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', 
		'\xF', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', 
		'\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', 
		'\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x11', '\x3', 
		'\x11', '\x3', '\x12', '\x3', '\x12', '\x3', '\x13', '\x3', '\x13', '\x3', 
		'\x13', '\x3', '\x13', '\x3', '\x13', '\x3', '\x14', '\x3', '\x14', '\x3', 
		'\x14', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\a', '\x14', '\xC7', 
		'\n', '\x14', '\f', '\x14', '\xE', '\x14', '\xCA', '\v', '\x14', '\x3', 
		'\x14', '\x3', '\x14', '\x3', '\x15', '\x3', '\x15', '\a', '\x15', '\xD0', 
		'\n', '\x15', '\f', '\x15', '\xE', '\x15', '\xD3', '\v', '\x15', '\x3', 
		'\x16', '\x6', '\x16', '\xD6', '\n', '\x16', '\r', '\x16', '\xE', '\x16', 
		'\xD7', '\x3', '\x16', '\x3', '\x16', '\x3', '\x17', '\x3', '\x17', '\x3', 
		'\x17', '\x3', '\x17', '\a', '\x17', '\xE0', '\n', '\x17', '\f', '\x17', 
		'\xE', '\x17', '\xE3', '\v', '\x17', '\x3', '\x17', '\x5', '\x17', '\xE6', 
		'\n', '\x17', '\x3', '\x17', '\x3', '\x17', '\x3', '\x17', '\x3', '\x17', 
		'\x4', '\xC8', '\xE1', '\x2', '\x18', '\x3', '\x3', '\x5', '\x4', '\a', 
		'\x5', '\t', '\x6', '\v', '\a', '\r', '\b', '\xF', '\t', '\x11', '\n', 
		'\x13', '\v', '\x15', '\f', '\x17', '\r', '\x19', '\xE', '\x1B', '\xF', 
		'\x1D', '\x10', '\x1F', '\x11', '!', '\x12', '#', '\x13', '%', '\x14', 
		'\'', '\x15', ')', '\x16', '+', '\x17', '-', '\x18', '\x3', '\x2', '\x5', 
		'\x5', '\x2', '\x43', '\\', '\x61', '\x61', '\x63', '|', '\x6', '\x2', 
		'\x32', ';', '\x43', '\\', '\x61', '\x61', '\x63', '|', '\x5', '\x2', 
		'\v', '\f', '\xF', '\xF', '\"', '\"', '\x2', '\xF1', '\x2', '\x3', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x5', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\a', '\x3', '\x2', '\x2', '\x2', '\x2', '\t', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\v', '\x3', '\x2', '\x2', '\x2', '\x2', '\r', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\xF', '\x3', '\x2', '\x2', '\x2', '\x2', '\x11', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x13', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x15', '\x3', '\x2', '\x2', '\x2', '\x2', '\x17', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x19', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1B', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x1D', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x1F', '\x3', '\x2', '\x2', '\x2', '\x2', '!', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '#', '\x3', '\x2', '\x2', '\x2', '\x2', '%', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\'', '\x3', '\x2', '\x2', '\x2', '\x2', ')', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '+', '\x3', '\x2', '\x2', '\x2', '\x2', '-', '\x3', 
		'\x2', '\x2', '\x2', '\x3', '/', '\x3', '\x2', '\x2', '\x2', '\x5', '\x31', 
		'\x3', '\x2', '\x2', '\x2', '\a', '\x33', '\x3', '\x2', '\x2', '\x2', 
		'\t', '\x35', '\x3', '\x2', '\x2', '\x2', '\v', '\x44', '\x3', '\x2', 
		'\x2', '\x2', '\r', '\x46', '\x3', '\x2', '\x2', '\x2', '\xF', 'O', '\x3', 
		'\x2', '\x2', '\x2', '\x11', 'V', '\x3', '\x2', '\x2', '\x2', '\x13', 
		'X', '\x3', '\x2', '\x2', '\x2', '\x15', '`', '\x3', '\x2', '\x2', '\x2', 
		'\x17', 'i', '\x3', '\x2', '\x2', '\x2', '\x19', 'u', '\x3', '\x2', '\x2', 
		'\x2', '\x1B', '\x83', '\x3', '\x2', '\x2', '\x2', '\x1D', '\x92', '\x3', 
		'\x2', '\x2', '\x2', '\x1F', '\xAA', '\x3', '\x2', '\x2', '\x2', '!', 
		'\xB7', '\x3', '\x2', '\x2', '\x2', '#', '\xB9', '\x3', '\x2', '\x2', 
		'\x2', '%', '\xBB', '\x3', '\x2', '\x2', '\x2', '\'', '\xC0', '\x3', '\x2', 
		'\x2', '\x2', ')', '\xCD', '\x3', '\x2', '\x2', '\x2', '+', '\xD5', '\x3', 
		'\x2', '\x2', '\x2', '-', '\xDB', '\x3', '\x2', '\x2', '\x2', '/', '\x30', 
		'\a', '*', '\x2', '\x2', '\x30', '\x4', '\x3', '\x2', '\x2', '\x2', '\x31', 
		'\x32', '\a', '+', '\x2', '\x2', '\x32', '\x6', '\x3', '\x2', '\x2', '\x2', 
		'\x33', '\x34', '\a', '=', '\x2', '\x2', '\x34', '\b', '\x3', '\x2', '\x2', 
		'\x2', '\x35', '\x36', '\a', 'G', '\x2', '\x2', '\x36', '\x37', '\a', 
		'z', '\x2', '\x2', '\x37', '\x38', '\a', 'r', '\x2', '\x2', '\x38', '\x39', 
		'\a', 't', '\x2', '\x2', '\x39', ':', '\a', 'g', '\x2', '\x2', ':', ';', 
		'\a', 'u', '\x2', '\x2', ';', '<', '\a', 'u', '\x2', '\x2', '<', '=', 
		'\a', 'k', '\x2', '\x2', '=', '>', '\a', 'q', '\x2', '\x2', '>', '?', 
		'\a', 'p', '\x2', '\x2', '?', '@', '\a', 'V', '\x2', '\x2', '@', '\x41', 
		'\a', '{', '\x2', '\x2', '\x41', '\x42', '\a', 'r', '\x2', '\x2', '\x42', 
		'\x43', '\a', 'g', '\x2', '\x2', '\x43', '\n', '\x3', '\x2', '\x2', '\x2', 
		'\x44', '\x45', '\a', '<', '\x2', '\x2', '\x45', '\f', '\x3', '\x2', '\x2', 
		'\x2', '\x46', 'G', '\a', 'G', '\x2', '\x2', 'G', 'H', '\a', 'p', '\x2', 
		'\x2', 'H', 'I', '\a', '\x65', '\x2', '\x2', 'I', 'J', '\a', 'q', '\x2', 
		'\x2', 'J', 'K', '\a', '\x66', '\x2', '\x2', 'K', 'L', '\a', 'k', '\x2', 
		'\x2', 'L', 'M', '\a', 'p', '\x2', '\x2', 'M', 'N', '\a', 'i', '\x2', 
		'\x2', 'N', '\xE', '\x3', '\x2', '\x2', '\x2', 'O', 'P', '\a', 'R', '\x2', 
		'\x2', 'P', 'Q', '\a', 't', '\x2', '\x2', 'Q', 'R', '\a', 'g', '\x2', 
		'\x2', 'R', 'S', '\a', 'h', '\x2', '\x2', 'S', 'T', '\a', 'k', '\x2', 
		'\x2', 'T', 'U', '\a', 'z', '\x2', '\x2', 'U', '\x10', '\x3', '\x2', '\x2', 
		'\x2', 'V', 'W', '\a', '.', '\x2', '\x2', 'W', '\x12', '\x3', '\x2', '\x2', 
		'\x2', 'X', 'Y', '\a', '\x44', '\x2', '\x2', 'Y', 'Z', '\a', 'k', '\x2', 
		'\x2', 'Z', '[', '\a', 'p', '\x2', '\x2', '[', '\\', '\a', '\x66', '\x2', 
		'\x2', '\\', ']', '\a', 'k', '\x2', '\x2', ']', '^', '\a', 'p', '\x2', 
		'\x2', '^', '_', '\a', 'i', '\x2', '\x2', '_', '\x14', '\x3', '\x2', '\x2', 
		'\x2', '`', '\x61', '\a', '\x44', '\x2', '\x2', '\x61', '\x62', '\a', 
		'k', '\x2', '\x2', '\x62', '\x63', '\a', 'p', '\x2', '\x2', '\x63', '\x64', 
		'\a', '\x66', '\x2', '\x2', '\x64', '\x65', '\a', 'k', '\x2', '\x2', '\x65', 
		'\x66', '\a', 'p', '\x2', '\x2', '\x66', 'g', '\a', 'i', '\x2', '\x2', 
		'g', 'h', '\a', 'u', '\x2', '\x2', 'h', '\x16', '\x3', '\x2', '\x2', '\x2', 
		'i', 'j', '\a', 'R', '\x2', '\x2', 'j', 'k', '\a', '\x63', '\x2', '\x2', 
		'k', 'l', '\a', 't', '\x2', '\x2', 'l', 'm', '\a', 'u', '\x2', '\x2', 
		'm', 'n', '\a', 'g', '\x2', '\x2', 'n', 'o', '\a', 'O', '\x2', '\x2', 
		'o', 'p', '\a', 'g', '\x2', '\x2', 'p', 'q', '\a', 'v', '\x2', '\x2', 
		'q', 'r', '\a', 'j', '\x2', '\x2', 'r', 's', '\a', 'q', '\x2', '\x2', 
		's', 't', '\a', '\x66', '\x2', '\x2', 't', '\x18', '\x3', '\x2', '\x2', 
		'\x2', 'u', 'v', '\a', '\x43', '\x2', '\x2', 'v', 'w', '\a', 'w', '\x2', 
		'\x2', 'w', 'x', '\a', 'v', '\x2', '\x2', 'x', 'y', '\a', 'q', '\x2', 
		'\x2', 'y', 'z', '\a', 'R', '\x2', '\x2', 'z', '{', '\a', '\x63', '\x2', 
		'\x2', '{', '|', '\a', 't', '\x2', '\x2', '|', '}', '\a', 'u', '\x2', 
		'\x2', '}', '~', '\a', 'g', '\x2', '\x2', '~', '\x7F', '\a', 'O', '\x2', 
		'\x2', '\x7F', '\x80', '\a', 'q', '\x2', '\x2', '\x80', '\x81', '\a', 
		'\x66', '\x2', '\x2', '\x81', '\x82', '\a', 'g', '\x2', '\x2', '\x82', 
		'\x1A', '\x3', '\x2', '\x2', '\x2', '\x83', '\x84', '\a', '\x43', '\x2', 
		'\x2', '\x84', '\x85', '\a', 'w', '\x2', '\x2', '\x85', '\x86', '\a', 
		'v', '\x2', '\x2', '\x86', '\x87', '\a', 'q', '\x2', '\x2', '\x87', '\x88', 
		'\a', '\x45', '\x2', '\x2', '\x88', '\x89', '\a', 't', '\x2', '\x2', '\x89', 
		'\x8A', '\a', 'g', '\x2', '\x2', '\x8A', '\x8B', '\a', '\x63', '\x2', 
		'\x2', '\x8B', '\x8C', '\a', 'v', '\x2', '\x2', '\x8C', '\x8D', '\a', 
		'g', '\x2', '\x2', '\x8D', '\x8E', '\a', 'O', '\x2', '\x2', '\x8E', '\x8F', 
		'\a', 'q', '\x2', '\x2', '\x8F', '\x90', '\a', '\x66', '\x2', '\x2', '\x90', 
		'\x91', '\a', 'g', '\x2', '\x2', '\x91', '\x1C', '\x3', '\x2', '\x2', 
		'\x2', '\x92', '\x93', '\a', 'P', '\x2', '\x2', '\x93', '\x94', '\a', 
		'w', '\x2', '\x2', '\x94', '\x95', '\a', 'n', '\x2', '\x2', '\x95', '\x96', 
		'\a', 'n', '\x2', '\x2', '\x96', '\x97', '\a', 'Q', '\x2', '\x2', '\x97', 
		'\x98', '\a', '\x64', '\x2', '\x2', '\x98', '\x99', '\a', 'l', '\x2', 
		'\x2', '\x99', '\x9A', '\a', 'g', '\x2', '\x2', '\x9A', '\x9B', '\a', 
		'\x65', '\x2', '\x2', '\x9B', '\x9C', '\a', 'v', '\x2', '\x2', '\x9C', 
		'\x9D', '\a', 'V', '\x2', '\x2', '\x9D', '\x9E', '\a', 't', '\x2', '\x2', 
		'\x9E', '\x9F', '\a', 'g', '\x2', '\x2', '\x9F', '\xA0', '\a', '\x63', 
		'\x2', '\x2', '\xA0', '\xA1', '\a', 'v', '\x2', '\x2', '\xA1', '\xA2', 
		'\a', 'o', '\x2', '\x2', '\xA2', '\xA3', '\a', 'g', '\x2', '\x2', '\xA3', 
		'\xA4', '\a', 'p', '\x2', '\x2', '\xA4', '\xA5', '\a', 'v', '\x2', '\x2', 
		'\xA5', '\xA6', '\a', 'O', '\x2', '\x2', '\xA6', '\xA7', '\a', 'q', '\x2', 
		'\x2', '\xA7', '\xA8', '\a', '\x66', '\x2', '\x2', '\xA8', '\xA9', '\a', 
		'g', '\x2', '\x2', '\xA9', '\x1E', '\x3', '\x2', '\x2', '\x2', '\xAA', 
		'\xAB', '\a', '\x45', '\x2', '\x2', '\xAB', '\xAC', '\a', 'q', '\x2', 
		'\x2', '\xAC', '\xAD', '\a', 'n', '\x2', '\x2', '\xAD', '\xAE', '\a', 
		'n', '\x2', '\x2', '\xAE', '\xAF', '\a', 'g', '\x2', '\x2', '\xAF', '\xB0', 
		'\a', '\x65', '\x2', '\x2', '\xB0', '\xB1', '\a', 'v', '\x2', '\x2', '\xB1', 
		'\xB2', '\a', 'k', '\x2', '\x2', '\xB2', '\xB3', '\a', 'x', '\x2', '\x2', 
		'\xB3', '\xB4', '\a', 'k', '\x2', '\x2', '\xB4', '\xB5', '\a', 'v', '\x2', 
		'\x2', '\xB5', '\xB6', '\a', '{', '\x2', '\x2', '\xB6', ' ', '\x3', '\x2', 
		'\x2', '\x2', '\xB7', '\xB8', '\a', '}', '\x2', '\x2', '\xB8', '\"', '\x3', 
		'\x2', '\x2', '\x2', '\xB9', '\xBA', '\a', '\x7F', '\x2', '\x2', '\xBA', 
		'$', '\x3', '\x2', '\x2', '\x2', '\xBB', '\xBC', '\a', 'p', '\x2', '\x2', 
		'\xBC', '\xBD', '\a', 'w', '\x2', '\x2', '\xBD', '\xBE', '\a', 'n', '\x2', 
		'\x2', '\xBE', '\xBF', '\a', 'n', '\x2', '\x2', '\xBF', '&', '\x3', '\x2', 
		'\x2', '\x2', '\xC0', '\xC8', '\a', ')', '\x2', '\x2', '\xC1', '\xC2', 
		'\a', '^', '\x2', '\x2', '\xC2', '\xC7', '\a', '^', '\x2', '\x2', '\xC3', 
		'\xC4', '\a', '^', '\x2', '\x2', '\xC4', '\xC7', '\a', ')', '\x2', '\x2', 
		'\xC5', '\xC7', '\v', '\x2', '\x2', '\x2', '\xC6', '\xC1', '\x3', '\x2', 
		'\x2', '\x2', '\xC6', '\xC3', '\x3', '\x2', '\x2', '\x2', '\xC6', '\xC5', 
		'\x3', '\x2', '\x2', '\x2', '\xC7', '\xCA', '\x3', '\x2', '\x2', '\x2', 
		'\xC8', '\xC9', '\x3', '\x2', '\x2', '\x2', '\xC8', '\xC6', '\x3', '\x2', 
		'\x2', '\x2', '\xC9', '\xCB', '\x3', '\x2', '\x2', '\x2', '\xCA', '\xC8', 
		'\x3', '\x2', '\x2', '\x2', '\xCB', '\xCC', '\a', ')', '\x2', '\x2', '\xCC', 
		'(', '\x3', '\x2', '\x2', '\x2', '\xCD', '\xD1', '\t', '\x2', '\x2', '\x2', 
		'\xCE', '\xD0', '\t', '\x3', '\x2', '\x2', '\xCF', '\xCE', '\x3', '\x2', 
		'\x2', '\x2', '\xD0', '\xD3', '\x3', '\x2', '\x2', '\x2', '\xD1', '\xCF', 
		'\x3', '\x2', '\x2', '\x2', '\xD1', '\xD2', '\x3', '\x2', '\x2', '\x2', 
		'\xD2', '*', '\x3', '\x2', '\x2', '\x2', '\xD3', '\xD1', '\x3', '\x2', 
		'\x2', '\x2', '\xD4', '\xD6', '\t', '\x4', '\x2', '\x2', '\xD5', '\xD4', 
		'\x3', '\x2', '\x2', '\x2', '\xD6', '\xD7', '\x3', '\x2', '\x2', '\x2', 
		'\xD7', '\xD5', '\x3', '\x2', '\x2', '\x2', '\xD7', '\xD8', '\x3', '\x2', 
		'\x2', '\x2', '\xD8', '\xD9', '\x3', '\x2', '\x2', '\x2', '\xD9', '\xDA', 
		'\b', '\x16', '\x2', '\x2', '\xDA', ',', '\x3', '\x2', '\x2', '\x2', '\xDB', 
		'\xDC', '\a', '\x31', '\x2', '\x2', '\xDC', '\xDD', '\a', '\x31', '\x2', 
		'\x2', '\xDD', '\xE1', '\x3', '\x2', '\x2', '\x2', '\xDE', '\xE0', '\v', 
		'\x2', '\x2', '\x2', '\xDF', '\xDE', '\x3', '\x2', '\x2', '\x2', '\xE0', 
		'\xE3', '\x3', '\x2', '\x2', '\x2', '\xE1', '\xE2', '\x3', '\x2', '\x2', 
		'\x2', '\xE1', '\xDF', '\x3', '\x2', '\x2', '\x2', '\xE2', '\xE5', '\x3', 
		'\x2', '\x2', '\x2', '\xE3', '\xE1', '\x3', '\x2', '\x2', '\x2', '\xE4', 
		'\xE6', '\a', '\xF', '\x2', '\x2', '\xE5', '\xE4', '\x3', '\x2', '\x2', 
		'\x2', '\xE5', '\xE6', '\x3', '\x2', '\x2', '\x2', '\xE6', '\xE7', '\x3', 
		'\x2', '\x2', '\x2', '\xE7', '\xE8', '\a', '\f', '\x2', '\x2', '\xE8', 
		'\xE9', '\x3', '\x2', '\x2', '\x2', '\xE9', '\xEA', '\b', '\x17', '\x2', 
		'\x2', '\xEA', '.', '\x3', '\x2', '\x2', '\x2', '\t', '\x2', '\xC6', '\xC8', 
		'\xD1', '\xD7', '\xE1', '\xE5', '\x3', '\b', '\x2', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace OpCheck.XmlConsumer
