//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from XmlConsumer.g4 by ANTLR 4.7

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace OpCheck.XmlConsumer {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IXmlConsumerListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7")]
[System.CLSCompliant(false)]
public partial class XmlConsumerBaseListener : IXmlConsumerListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="XmlConsumerParser.xmlConsumerExpressionFile"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterXmlConsumerExpressionFile([NotNull] XmlConsumerParser.XmlConsumerExpressionFileContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XmlConsumerParser.xmlConsumerExpressionFile"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitXmlConsumerExpressionFile([NotNull] XmlConsumerParser.XmlConsumerExpressionFileContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XmlConsumerParser.xmlConsumerScript"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterXmlConsumerScript([NotNull] XmlConsumerParser.XmlConsumerScriptContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XmlConsumerParser.xmlConsumerScript"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitXmlConsumerScript([NotNull] XmlConsumerParser.XmlConsumerScriptContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XmlConsumerParser.optionsTuple"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOptionsTuple([NotNull] XmlConsumerParser.OptionsTupleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XmlConsumerParser.optionsTuple"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOptionsTuple([NotNull] XmlConsumerParser.OptionsTupleContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XmlConsumerParser.optionsList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOptionsList([NotNull] XmlConsumerParser.OptionsListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XmlConsumerParser.optionsList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOptionsList([NotNull] XmlConsumerParser.OptionsListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ExpressionTypeOption</c>
	/// labeled alternative in <see cref="XmlConsumerParser.option"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpressionTypeOption([NotNull] XmlConsumerParser.ExpressionTypeOptionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ExpressionTypeOption</c>
	/// labeled alternative in <see cref="XmlConsumerParser.option"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpressionTypeOption([NotNull] XmlConsumerParser.ExpressionTypeOptionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>EncodingOption</c>
	/// labeled alternative in <see cref="XmlConsumerParser.option"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEncodingOption([NotNull] XmlConsumerParser.EncodingOptionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>EncodingOption</c>
	/// labeled alternative in <see cref="XmlConsumerParser.option"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEncodingOption([NotNull] XmlConsumerParser.EncodingOptionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>PrefixOption</c>
	/// labeled alternative in <see cref="XmlConsumerParser.option"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrefixOption([NotNull] XmlConsumerParser.PrefixOptionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>PrefixOption</c>
	/// labeled alternative in <see cref="XmlConsumerParser.option"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrefixOption([NotNull] XmlConsumerParser.PrefixOptionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>BindingOption</c>
	/// labeled alternative in <see cref="XmlConsumerParser.option"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBindingOption([NotNull] XmlConsumerParser.BindingOptionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>BindingOption</c>
	/// labeled alternative in <see cref="XmlConsumerParser.option"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBindingOption([NotNull] XmlConsumerParser.BindingOptionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>BindingsOption</c>
	/// labeled alternative in <see cref="XmlConsumerParser.option"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBindingsOption([NotNull] XmlConsumerParser.BindingsOptionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>BindingsOption</c>
	/// labeled alternative in <see cref="XmlConsumerParser.option"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBindingsOption([NotNull] XmlConsumerParser.BindingsOptionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ParseMethodOption</c>
	/// labeled alternative in <see cref="XmlConsumerParser.option"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParseMethodOption([NotNull] XmlConsumerParser.ParseMethodOptionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ParseMethodOption</c>
	/// labeled alternative in <see cref="XmlConsumerParser.option"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParseMethodOption([NotNull] XmlConsumerParser.ParseMethodOptionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>AutoParseModeOption</c>
	/// labeled alternative in <see cref="XmlConsumerParser.option"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAutoParseModeOption([NotNull] XmlConsumerParser.AutoParseModeOptionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>AutoParseModeOption</c>
	/// labeled alternative in <see cref="XmlConsumerParser.option"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAutoParseModeOption([NotNull] XmlConsumerParser.AutoParseModeOptionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>AutoCreateModeOption</c>
	/// labeled alternative in <see cref="XmlConsumerParser.option"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAutoCreateModeOption([NotNull] XmlConsumerParser.AutoCreateModeOptionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>AutoCreateModeOption</c>
	/// labeled alternative in <see cref="XmlConsumerParser.option"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAutoCreateModeOption([NotNull] XmlConsumerParser.AutoCreateModeOptionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>NullObjectTreatmentModeOption</c>
	/// labeled alternative in <see cref="XmlConsumerParser.option"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNullObjectTreatmentModeOption([NotNull] XmlConsumerParser.NullObjectTreatmentModeOptionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>NullObjectTreatmentModeOption</c>
	/// labeled alternative in <see cref="XmlConsumerParser.option"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNullObjectTreatmentModeOption([NotNull] XmlConsumerParser.NullObjectTreatmentModeOptionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>CollectivityOption</c>
	/// labeled alternative in <see cref="XmlConsumerParser.option"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCollectivityOption([NotNull] XmlConsumerParser.CollectivityOptionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>CollectivityOption</c>
	/// labeled alternative in <see cref="XmlConsumerParser.option"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCollectivityOption([NotNull] XmlConsumerParser.CollectivityOptionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XmlConsumerParser.stringLiteralsList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStringLiteralsList([NotNull] XmlConsumerParser.StringLiteralsListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XmlConsumerParser.stringLiteralsList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStringLiteralsList([NotNull] XmlConsumerParser.StringLiteralsListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XmlConsumerParser.objectMappingBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterObjectMappingBlock([NotNull] XmlConsumerParser.ObjectMappingBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XmlConsumerParser.objectMappingBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitObjectMappingBlock([NotNull] XmlConsumerParser.ObjectMappingBlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XmlConsumerParser.mappingList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMappingList([NotNull] XmlConsumerParser.MappingListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XmlConsumerParser.mappingList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMappingList([NotNull] XmlConsumerParser.MappingListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>NullMapping</c>
	/// labeled alternative in <see cref="XmlConsumerParser.simpleMapping"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNullMapping([NotNull] XmlConsumerParser.NullMappingContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>NullMapping</c>
	/// labeled alternative in <see cref="XmlConsumerParser.simpleMapping"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNullMapping([NotNull] XmlConsumerParser.NullMappingContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>NullMappingWithOptions</c>
	/// labeled alternative in <see cref="XmlConsumerParser.simpleMapping"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNullMappingWithOptions([NotNull] XmlConsumerParser.NullMappingWithOptionsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>NullMappingWithOptions</c>
	/// labeled alternative in <see cref="XmlConsumerParser.simpleMapping"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNullMappingWithOptions([NotNull] XmlConsumerParser.NullMappingWithOptionsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>StringMapping</c>
	/// labeled alternative in <see cref="XmlConsumerParser.simpleMapping"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStringMapping([NotNull] XmlConsumerParser.StringMappingContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>StringMapping</c>
	/// labeled alternative in <see cref="XmlConsumerParser.simpleMapping"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStringMapping([NotNull] XmlConsumerParser.StringMappingContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>StringMappingWithOptions</c>
	/// labeled alternative in <see cref="XmlConsumerParser.simpleMapping"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStringMappingWithOptions([NotNull] XmlConsumerParser.StringMappingWithOptionsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>StringMappingWithOptions</c>
	/// labeled alternative in <see cref="XmlConsumerParser.simpleMapping"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStringMappingWithOptions([NotNull] XmlConsumerParser.StringMappingWithOptionsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ObjectMapping</c>
	/// labeled alternative in <see cref="XmlConsumerParser.complexMapping"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterObjectMapping([NotNull] XmlConsumerParser.ObjectMappingContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ObjectMapping</c>
	/// labeled alternative in <see cref="XmlConsumerParser.complexMapping"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitObjectMapping([NotNull] XmlConsumerParser.ObjectMappingContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ObjectMappingWithOptions</c>
	/// labeled alternative in <see cref="XmlConsumerParser.complexMapping"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterObjectMappingWithOptions([NotNull] XmlConsumerParser.ObjectMappingWithOptionsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ObjectMappingWithOptions</c>
	/// labeled alternative in <see cref="XmlConsumerParser.complexMapping"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitObjectMappingWithOptions([NotNull] XmlConsumerParser.ObjectMappingWithOptionsContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace OpCheck.XmlConsumer
